[project]
name = "lingue-python"
version = "0.1.0"
description = "Loading tests for Python web app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litestar[standard]>=2.16.0",
]
